stages:
  - build

variables:
  IMAGE_DB: $CI_REGISTRY_IMAGE/db:$CI_COMMIT_REV_SLUG
  IMAGE_BACKEND: $CI_REGISTRY_IMAGE/backend:$CI_COMMIT_REV_SLUG
  IMAGE_FRONTEND: $CI_REGISTRY_IMAGE/frontend:$CI_COMMIT_REV_SLUG

build:
  stage: build
  image: ondrejsika/ci
  script:
    - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
    - docker-compose build
    - docker-compose push
