image: ondrejsika/ci

stages:
  - build
  - deploy dev
  - deploy prod

variables:
  IMAGE_DB: $CI_REGISTRY_IMAGE/db:$CI_COMMIT_SHORT_SHA-$CI_PIPELINE_ID-$CI_COMMIT_REF_SLUG
  IMAGE_BACKEND: $CI_REGISTRY_IMAGE/backend:$CI_COMMIT_SHORT_SHA-$CI_PIPELINE_ID-$CI_COMMIT_REF_SLUG
  IMAGE_FRONTEND: $CI_REGISTRY_IMAGE/frontend:$CI_COMMIT_SHORT_SHA-$CI_PIPELINE_ID-$CI_COMMIT_REF_SLUG
  DEV_NAME: dev-$CI_COMMIT_REF_SLUG
  PROD_NAME: prod

build:
  stage: build
  variables:
    MYSQL_ROOT_PASSWORD: root
  script:
    - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
    - docker-compose config
    - docker-compose build
    - docker-compose push

deploy dev:
  stage: deploy dev
  script:
    - kubectl create ns $KUBE_NAMESPACE || true
    - helm upgrade --install $DEV_NAME ./helm/adbros
      --set backendImage=$IMAGE_BACKEND
      --set frontendImage=$IMAGE_FRONTEND
      --set mysqlImage=$IMAGE_DB
      --set backendHost=$CI_COMMIT_REF_SLUG-backend.k8s.sikademo.com
      --set frontendHost=$CI_COMMIT_REF_SLUG.k8s.sikademo.com
      --set frontendReplicas=1
      --set backendReplicas=1
    - kubectl rollout status deploy $DEV_NAME-backend
    - kubectl rollout status deploy $DEV_NAME-frontend
    - kubectl rollout status sts $DEV_NAME
    - sleep 10
  environment:
    name: dev/$CI_COMMIT_REF_SLUG
    url: https://$CI_COMMIT_REF_SLUG.k8s.sikademo.com
    on_stop: destroy dev
  except:
    - master

destroy dev:
  when: manual
  stage: deploy dev
  script:
    - helm uninstall $DEV_NAME
  environment:
    name: dev/$CI_COMMIT_REF_SLUG
    action: stop
  except:
    - master

deploy prod:
  stage: deploy prod
  script:
    - kubectl create ns $KUBE_NAMESPACE || true
    - helm upgrade --install $PROD_NAME ./helm/adbros
      --set backendImage=$IMAGE_BACKEND
      --set frontendImage=$IMAGE_FRONTEND
      --set mysqlImage=$IMAGE_DB
      --set backendHost=backend.k8s.sikademo.com
      --set frontendHost=frontend.k8s.sikademo.com
    - kubectl rollout status deploy $PROD_NAME-backend
    - kubectl rollout status deploy $PROD_NAME-frontend
    - kubectl rollout status sts $PROD_NAME
    - sleep 10
  environment:
    name: prod
    url: https://frontend.k8s.sikademo.com
  only:
    - master
