image: ondrejsika/ci

stages:
  - build
  - deploy

variables:
  IMAGE_DB: $CI_REGISTRY_IMAGE/db:$CI_COMMIT_REF_SLUG
  IMAGE_BACKEND: $CI_REGISTRY_IMAGE/backend:$CI_COMMIT_REF_SLUG
  IMAGE_FRONTEND: $CI_REGISTRY_IMAGE/frontend:$CI_COMMIT_REF_SLUG

build:
  stage: build
  variables:
    MYSQL_ROOT_PASSWORD: root
  script:
    - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
    - docker-compose config
    - docker-compose build
    - docker-compose push

deploy:
  stage: deploy
  script:
    - kubectl create ns $KUBE_NAMESPACE || true
    - kubectl apply -f k8s
  environment:
    name: prod
    url: https://frontend.k8s.sikademo.com
