apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-backend
  labels:
    project: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      project: {{ .Release.Name }}
      app: backend
  replicas: {{ .Values.backendReplicas }}
  template:
    metadata:
      labels:
        project: {{ .Release.Name }}
        app: backend
    spec:
      containers:
        - name: backend
          image: {{ .Values.backendImage }}
          resources:
            requests:
              cpu: 3m
              memory: 40Mi
            limits:
              cpu: 10m
              memory: 50Mi
          env:
            - name: MYSQL_HOST
              value: {{ .Release.Name }}
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}
                  key: MYSQL_DATABASE
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}
                  key: MYSQL_ROOT_PASSWORD
          ports:
            - containerPort: 80
