apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-backend
  labels:
    project: {{ .Release.Name }}
spec:
  ports:
    - port: 80
  selector:
    project: {{ .Release.Name }}
    app: backend
