apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-frontend
  labels:
    project: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      project: {{ .Release.Name }}
      app: frontend
  replicas: {{ .Values.frontendReplicas }}
  template:
    metadata:
      labels:
        project: {{ .Release.Name }}
        app: frontend
    spec:
      containers:
        - name: frontend
          image: {{ .Values.frontendImage }}
          resources:
            requests:
              cpu: 3m
              memory: 40Mi
            limits:
              cpu: 10m
              memory: 50Mi
          env:
            - name: API_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}
                  key: API_URL
          ports:
            - containerPort: 80
