apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}
  labels:
    project: {{ .Release.Name }}
spec:
  serviceName: {{ .Release.Name }}
  selector:
    matchLabels:
      project: {{ .Release.Name }}
      app: mysql
  replicas: 1
  template:
    metadata:
      labels:
        project: {{ .Release.Name }}
        app: mysql
    spec:
      containers:
        - name: mysql
          image: {{ .Values.mysqlImage }}
          resources:
            requests:
              cpu: 50m
              memory: 100Mi
          env:
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}
                  key: MYSQL_DATABASE
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}
                  key: MYSQL_ROOT_PASSWORD
          ports:
            - containerPort: 3306
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql
      volumes:
        - name: mysql
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}
