apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
stringData:
  MYSQL_DATABASE: default
  MYSQL_ROOT_PASSWORD: {{ .Values.mysqlRootPassword }}
  API_URL: https://{{ .Values.backendHost }}
